### ISSUE TITLE
Enhancements for Optional Bucket Creation and Improved Key Handling

### ISSUE THREAD

**Issue by pcanto-hopeit** [hopeit-git/hopeit.aws#6]
### Enhancements and Clarifications Needed Based on Latest Pull Request Review by @leosmerling-hopeit:

1. **Bucket Creation as a Method and Optional for Initialization:**
   - Make bucket creation a method within `ObjectStorage`. Note this is not recommended to use in production environments
   - Remove the create_buacket option.

2. **Prefix Handling:**
   - Ensure the prefix always ends with a `/`.
   - Simplify key construction by removing trailing `/` from both `partition_key` and `prefix` before concatenation.
   - Verify that `partition_key` and `prefix` are not already stripped of trailing `/`.

3. **File Name Construction:**
   - Streamline file name construction considering the presence of `partition_key` and `prefix`.

4. **Wildcard and Partition Date Format:**
   - Make consistent default to `False` on `recursive`.
   - Clarify this behavior in the documentation.

**Comment by leosmerling-hopeit** [comment]
I've asked ChatGPT to rewrite the issue description to make it concise. Is this correct?

### Enhancements and Clarifications Needed Based on Latest Pull Request Review by @leosmerling-hopeit:

1. **Bucket Creation as a Method and Optional for Initialization:**
   - Make bucket creation a method within `ObjectStorage`.
   - Ensure it remains optional and configurable in the settings.
   - Account for different permissions required for bucket creation in various scenarios.

2. **Prefix Handling:**
   - Ensure the prefix always ends with a `/`.
   - Simplify key construction by removing trailing `/` from both `partition_key` and `prefix` before concatenation.
   - Verify that `partition_key` and `prefix` are not already stripped of trailing `/`.

3. **File Name Construction:**
   - Streamline file name construction considering the presence of `partition_key` and `prefix`.

4. **Wildcard and Partition Date Format:**
   - When `partition_dateformat` is configured, set `recursive` to `True` by default.
   - Review if this default setting is appropriate.
   - Clarify this behavior in the documentation.

**Comment by pcanto-hopeit** [comment]
Pretty impressive! I will update the issue definition. Thanks!
